# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: CDSS StateMod Developer Manual
pages:
- Home: index.md
- About:  about.md 
- Introduction and Protocols:  introduction.md
- Fortran resources: fortran.md
- Configure Development Environment:  configure-dev-env.md
- Code Overview:  code-overview.md
- Model Input:  model-input.md
- Model Output:  model-output.md
- Running StateMod:  running-statemod.md
- StateMod Utilities:  statemod-utilities.md
- Error Handling and Logging:  error-handling-logging.md
- Revision Control:  revision-control.md
- Testing:  testing.md
- Build Process:  build-process.md
- Documenting Code:  documentation.md
- Adding an Operating Rule:  add-operating-rule.md
theme: readthedocs
repo_url:  https://github.com/OpenWaterFoundation/owf-learn-statemod-dev
site_description:  Colorado's Decision Support Systems StateMod model developer documentation
site_author:  Open Water Foundation
site_favicon:  StateMod-favicon.png
#copyright:  Copyright Open Water Foundation
#extra_css:
#- css/extra.css
# Defaults to all JavaScript in the docs folder
# extra_javascript:
